### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by jaxxstorm** [oun/pulumi-flux#1]
Hi there! Thanks so much for contributing the provider!

It would help the display in the registry if you could add a docs directory with some information about the provider, see this example:

https://github.com/lbrlabs/pulumi-harness/tree/main/docs

**Comment by oun** [comment]
Hi @jaxxstorm,
I added some doc as your suggestion. 
https://github.com/oun/pulumi-flux/tree/main/docs
Please let me know if it miss something.

Thank you.

**Comment by jaxxstorm** [comment]
Looks great! Thanks!
