### ISSUE TITLE
New Flux Terraform Release: 0.24

### ISSUE THREAD

**Issue by alewis001** [oun/pulumi-flux#7]
There's a new release of the terraform provider https://registry.terraform.io/providers/fluxcd/flux/latest. With version 0.23+ it appears that the API has switched from install/sync resources to a single bootstrap resource.

Would that change in API be reflected in this provider?

**Comment by oun** [comment]
Thanks for update. I will update this provider to reflect changed from new version.

**Comment by alewis001** [comment]
Ok, great news. Thanks

**Comment by LockedThread** [comment]
@oun any updates?

**Comment by oun** [comment]
I'm still working on it. I will release in a couple of days.

**Comment by LockedThread** [comment]
> I'm still working on it. I will release in a couple of days.

Alright, we all really appreciate it. If you need any community help let us know.

**Comment by oun** [comment]
I have released version [0.25.3](https://github.com/oun/pulumi-flux/releases/tag/v0.25.3) and add some example flux-bootstrap-git resource [here](https://github.com/oun/pulumi-flux/tree/main/examples/nodejs/flux-bootstrap-git).
