### ISSUE TITLE
403 couldn't load pulumi flux 

### ISSUE THREAD

**Issue by houssems** [oun/pulumi-flux#8]
Hi,

From yesterday, the pipeline couldn't get and load pulumi flux 

> error: could not load plugin for flux provider 'urn:pulumi:odb_dev::aks::pulumi:providers:flux::default_0_20_0': Could not automatically download and install resource plugin 'pulumi-resource-flux' at version v0.20.0, install the plugin using `pulumi plugin install resource flux v0.20.0`: error downloading provider flux to file: failed to download plugin: flux-0.20.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-flux-v0.20.0-linux-amd64.tar.gz

`version: pulumi 3.60.0 x64`

**Comment by oun** [comment]
This is a pulumi issue. Can you try installing plugin before running pulumi up?
`pulumi plugin install resource flux v0.22.2 --server github://api.github.com/oun`

Same issues here: https://github.com/pulumi/pulumi/issues/10882
